title: 钢困的 blog
description: 慢慢地，但永远向前～
show_downloads: false
host: zhengqk.com
baseurl: ""
google_analytics:
theme: jekyll-theme-hacker
paginate: 5
highlighter: rouge
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "钢困"
